networks:
  miniprint_local:
  rdphoneypot_local:

services:

# Miniprint service
  miniprint:
    build: .
    container_name: miniprint
    restart: always
#    cpu_count: 1
#    cpus: 0.25
    networks:
     - miniprint_local
    ports:
      - "9100:9100"
    image: khulnasoft/miniprint:24.04
    read_only: true
    volumes:
     - $HOME/cyberpot/data/miniprint/log/:/opt/miniprint/log/
     - $HOME/cyberpot/data/miniprint/uploads/:/opt/miniprint/uploads/

# RDPHoneypot service
  rdphoneypot:
    container_name: rdphoneypot
    restart: always
    depends_on:
      cyberpotinit:
        condition: service_healthy
    networks:
     - rdphoneypot_local
    ports:
     - "3389:3389"
    image: ${CYBERPOT_REPO}/rdphoneypot:${CYBERPOT_VERSION}
    pull_policy: ${CYBERPOT_PULL_POLICY}
    read_only: true
    volumes:
     - ${CYBERPOT_DATA_PATH}/rdphoneypot/cert:/opt/rdphoneypot/cert
     - ${CYBERPOT_DATA_PATH}/rdphoneypot/log:/opt/rdphoneypot/log
